version: '3'

services:
  db:
    image: postgres
    container_name: swa_postgres
    networks:
      - db_user
      - db_admin
    expose:
      - "5432"
    env_file:
      - ./.env
    volumes:
      - ./scripts/create-multiple-databases.sh:/docker-entrypoint-initdb.d/create-multiple-databases.sh
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "psql", "${POSTGRES_USER}", "-h", "0.0.0.0", "-d", "swa_statistics"]
      interval: 5s
    restart: on-failure
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: swa_pgadmin4
    networks:
      - db_admin
    ports:
      - "8001:80"
    depends_on:
      - "db"
    env_file:
      - ./.env
    volumes:
      - /var/lib/pgadmin
    restart: on-failure

  app:
    container_name: swa_statistics
    build:
      context: .
      target: ${BUILD_TYPE}
    environment:
      - "SERVER_PORT=${SERVICE_PORT}"
    networks:
      - db_user
    depends_on:
      db:
        condition: service_healthy 
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    restart: on-failure

networks:
  db_user:
    driver: bridge
  db_admin:
    driver: bridge
    
    