FROM node:lts as base

ARG STATISTICS_PORT

# Create app directory
RUN mkdir -p /usr/src/statistics
WORKDIR /usr/src/statistics
EXPOSE ${STATISTICS_PORT}

# Install dependencies
COPY package.json .
COPY package-lock.json .

FROM base
ENV NODE_ENV=production
RUN npm ci
COPY . .
CMD [ "node", "index.js" ]