FROM node:lts as base

ARG STATISTICS_PORT

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
EXPOSE ${STATISTICS_PORT}

# Install dependencies
COPY package.json .
COPY package-lock.json .

FROM base
ENV NODE_ENV=testing
RUN npm install -g jest && npm install
COPY . .
CMD [ "npm", "test" ]
