version: '3'

services:
  db:
    image: postgres
    container_name: swa_postgres
    networks:
      - db_user
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_TEST_DB}
    volumes:
      - /var/lib/postgresql/data
    restart: on-failure
  
  app:
    container_name: swa_statistics
    build:
      context: .
      dockerfile: Dockerfile.test
      args: 
        STATISTICS_PORT: ${STATISTICS_PORT}
    environment:
      - "SERVER_PORT=${STATISTICS_PORT}"
    networks:
      - db_user
    depends_on:
      - "db"
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - "${STATISTICS_PORT}:${STATISTICS_PORT}"
    restart: on-failure

networks:
  db_user:
    driver: bridge