FROM node:lts as base

ARG STATISTICS_PORT

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
EXPOSE ${STATISTICS_PORT}

# Install dependencies
COPY package.json .
COPY package-lock.json .

FROM base
ENV NODE_ENV=development
RUN npm install -g nodemon && npm install
COPY . .
CMD ["nodemon", "-L", "index.js" ]