FROM node:lts as base

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
EXPOSE 8080

# Install dependencies
COPY package.json .
COPY package-lock.json .

FROM base
ENV NODE_ENV=testing
RUN npm install -g jest && npm install
COPY . .
CMD [ "npm", "test" ]
